language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

php:
    - 5.5
    - 5.6
    - 7.0
    - hhvm

env:
    - SYMFONY_VERSION=2.7.*
    - SYMFONY_VERSION=2.8.*
    - SYMFONY_VERSION=3.0.*

matrix:
    fast_finish: true
    allow_failures:
        - php: 7.0
        - php: hhvm

before_script:
    - composer require symfony/framework-bundle:${SYMFONY_VERSION} --no-update

install: composer install --prefer-dist --no-interaction

script: phpunit
